# Generated by Django 5.0.3 on 2024-03-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_note_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
    ]
