# Generated by Django 5.0.3 on 2024-03-12 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notes.tag'),
            preserve_default=False,
        ),
    ]
