# Generated by Django 5.0.3 on 2024-03-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_fact_alter_note_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField(default=0)),
                ('promocao', models.BooleanField(default=False)),
            ],
        ),
    ]
