# Generated by Django 5.0.3 on 2024-04-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
    ]
