# Generated by Django 5.0.3 on 2024-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_moeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='moeda',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
