# Generated by Django 5.0.3 on 2024-05-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_moeda_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='preco',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
    ]
